### ISSUE TITLE
[Release] Official Release Checklist

### ISSUE THREAD

**Issue by ejektaflex** [ejektaflex/Bountiful-Fabric#5]
Things that still need to be done before a release:

Initial release:
- [x] Implement message system to keep board item joins/leaves in sync
- [x] Only track taken bounty slots per player
- [x] Add prefix to mob bounties to make them more clear
- [x] Reorganize command tree and ensure it gives meaningful feedback to players
- [x] Fix farmer objectives showing up in certain circumstances
- [x] Allow for data exclusion in the config
- [x] Turning in bounties should play a sound and perhaps give a notification
- [x] Add an ERROR read fail condition for Kambrik configs
- [x] Add logic that removes expired bounties when ticking every perhaps 5 seconds
- [x] Newly added decrees should tick and get set every second, not every bounty tick
- [x] Fix objective progress showing as zero until fully completed
- [x] Add overall weight mult for pools, that multiplies into all items
- [x] `/bo gen decree` should suggest existing decree ids
- [x] Replace the `copydata` packet with a CopyToClipboardMessage
- [x] Revise mod compat for 1.17
- [x] Ensure worldgen still works and make it configurable
- [x] Ensure initial config gets generated
- [x] Ensure this works with ModMenu

Pushed off to a later release:
- [-] Implement item tag bounties
- [-] Auto forbid mixing of certain item bounties and item tag bounties (we can already forbid manually)
- [x] Allow specifying `range` and `unitWorth` in the pool addhand command
- [ ] Mystery Decrees art and stuff

**Comment by JOEYHHH4** [comment]
Good luck! I'll download it once it's finished

**Comment by ejektaflex** [comment]
Thanks, I'm almost there! Getting a bit closer every day :^)

**Comment by JOEYHHH4** [comment]
Is it gonna be for 1.16.x, 1.17.x or both?

**Comment by ejektaflex** [comment]
This will be for 1.17.x and onward.

**Comment by thijsi123** [comment]
Nice. I can't wait to play this on 1.17.

**Comment by ejektaflex** [comment]
In case you're wondering what is different, here is what there is to look forward to!

* Bounty boards now have instanced inventory copies per player. This means that the contents of a given bounty board are the same for each player, but each player can take their own copy of the same bounty. So, if you see a really good bounty on the board, you can take it and tell your friends. They can take their own copies as well!
* Bounty balancing, as per usual. It's impossible to get this nailed down perfectly, but with the reputation and rarity changes, it balances itself out a bit.
* Rarity means what it should mean now. Now, more rare bounty rewards show up less often.
* Reputation! It's quite simple: Each board has a "reputation" number. The more bounties that get submitted, the higher the number goes! As your reputation goes up, you'll see more rare bounties more often. Some bounty rewards may not even show up until you hit extremely high reputation.
* Submitting bounties now gives you a little bit of experience and plays a sound.
* Datapacks have been reworked. They have a slightly different layout, which makes them incompatible with packs made for Forge (but Forge uses different mods anyway, so whatever). On the flip side, we can now load decrees and pools from both datapacks AND the config folder! And there's a sweet command that makes adding new content a bit easier without ever touching the config files.

I've got [a Discord server](https://discord.gg/BaH88W9) set up for my own mod development, in case you want to ask any questions there.

**Comment by ExpertSniper15** [comment]
Will there be a 1.14 version?

**Comment by ejektaflex** [comment]
No, just 1.17.1+ for Fabric. There does exist a 1.14 release for Forge :^)

**Comment by ejektaflex** [comment]
@ExpertSniper15 @JOEYHHH4 @thijsi123 
[Download for Fabric, 1.17.1](https://modrinth.com/mod/bountiful)
Make sure you also have Kambrik and Fabric Language Kotlin, as stated in the description. Enjoy, and please report bugs!

**Comment by JOEYHHH4** [comment]
I play on 1.16.5 
sad

**Comment by thijsi123** [comment]
> @ExpertSniper15 @JOEYHHH4 @thijsi123
> [Download for Fabric, 1.17.1](https://modrinth.com/mod/bountiful)
> Make sure you also have Kambrik and Fabric Language Kotlin, as stated in the description. Enjoy, and please report bugs!

Thank you. :)
